name: "Bezzubick MCPlay"
description: "Ютубер и стример по Minecraft. Уютный канал без мата: стримы, видео, комьюнити, планы."
url: "https://httydcraft.github.io/BezzubickMCPlay"
language: ru
favicon: "/assets/avatar.png"
image: "/assets/avatar.png"
