name: Deploy Publish Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Build and Generate Site
        run: swift run

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './Output'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
