name: Update Social Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

concurrency:
  group: update-social-data
  cancel-in-progress: false

jobs:
  update-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run script to update data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          YOUR_YOUTUBE_CHANNEL_ID: ${{ secrets.YOUR_YOUTUBE_CHANNEL_ID }}
          YOUR_TWITCH_USERNAME: ${{ secrets.YOUR_TWITCH_USERNAME }}
          YOUR_VK_GROUP_ID: ${{ secrets.YOUR_VK_GROUP_ID }}
          YOUR_VK_USER_ID: ${{ secrets.YOUR_VK_USER_ID }}
          VK_GROUP_ACCESS_TOKEN: ${{ secrets.VK_GROUP_ACCESS_TOKEN }}
          VK_USER_ACCESS_TOKEN: ${{ secrets.VK_USER_ACCESS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_CHAT_ID: ${{ secrets.TELEGRAM_CHANNEL_CHAT_ID }}
          INSTAGRAM_BUSINESS_ACCOUNT_ID: ${{ secrets.INSTAGRAM_BUSINESS_ACCOUNT_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          YOUR_X_USER_ID: ${{ secrets.YOUR_X_USER_ID }}
          TIKAPI_IO_API_KEY: ${{ secrets.TIKAPI_IO_API_KEY }}
          YOUR_TIKTOK_USERNAME: ${{ secrets.YOUR_TIKTOK_USERNAME }}
        run: python scripts/update_data.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json streams_history.json
          git diff --staged --quiet || git commit -m "Auto-update data.json + streams_history.json"
          git push